version: "2"

run:
  allow-parallel-runners: true

linters:
  default: none
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - ginkgolinter
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused

  settings:
    revive:
      rules:
        - name: comment-spacings
        - name: import-shadowing
    lll:
      line-length: 120
      tab-width: 1

  exclusions:
    rules:
      # Exclude lll for kubebuilder RBAC annotations (cannot be line-wrapped)
      - linters:
          - lll
        source: "^// \\+kubebuilder:"
      # Allow dupl in controller files (expected structural similarity in Reconcile functions)
      - linters:
          - dupl
        paths:
          - internal/controller/
        text: ".*"
      # Allow dot imports in test files (Ginkgo/Gomega standard practice)
      - linters:
          - revive
        text: "dot-imports"
        paths:
          - _test\.go

formatters:
  enable:
    - gofmt
    - goimports
